In [58]:
from bs4 import BeautifulSoup
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import pandas as pd
import GetCategory as cate
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys


# Musical = ["http://mticket.interpark.com/genre?Genre=MU&cat=11007","http://mticket.interpark.com/genre?Genre=MU&cat=11008","http://mticket.interpark.com/genre?Genre=MU&cat=11009","http://mticket.interpark.com/genre?Genre=MU&cat=11010"]#오리지널/내한, 라이선스, 창작 뮤지컬, 넌버벌 퍼포먼스

### Crawling Setup
def get_urls_list(url):
    urls_list = []
    # ChromeDriver 경로
    chromedriver_path = "C:\\Users\\cokip\\Downloads\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe" # 정확한 파일 경로 입력
    
    # Service 객체 생성
    service = Service(chromedriver_path)
    
    # WebDriver 생성
    browser = webdriver.Chrome(service=service)
    
    # 암시적 대기
    browser.implicitly_wait(3)

    browser.get(url)

    while 1:
        try:
            browser.find_element(By.CLASS_NAME, "moreBtn").send_keys(Keys.ENTER)
            time.sleep(0.1)
        except:
            break

    html = browser.page_source
    soup = BeautifulSoup(html, 'html.parser')

    # score 크롤링 userBoardList
    urls = soup.find("div", {"class": "swiper-slide swiper-slide-active"})
    urls = urls.find("ul", {"class": "allListWrap"})
    for url in urls.find_all("li"):
        urls_list.append("https:" + url.find("a")["href"])

    browser.close()
    return urls_list

print(get_urls_list('https://mticket.interpark.com/Genre?Genre=DR'))

['https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24006928&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017573&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012128&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=L0000104&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014092&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015518&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=22001159&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23005704&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23008491&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015841&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21013249&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=22014277&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015530&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24001916&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24002802&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014788&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016741&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21013096&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017904&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016054&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=22001006&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014333&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24004660&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014157&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012547&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017907&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21002623&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24008626&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017527&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23005252&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24000171&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015331&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011787&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23018094&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016450&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016323&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23003616&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23004562&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23011814&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21007446&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23016780&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016099&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013962&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015317&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=18001569&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013510&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017500&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24007536&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011341&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016640&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24001143&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014861&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014723&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016815&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015988&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=22007314&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24002220&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015580&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015947&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016449&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017888&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017879&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24009362&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013365&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014410&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016592&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011798&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014759&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015587&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=19001540&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24007080&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011257&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011577&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016342&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015496&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017161&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=18013732&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016023&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011113&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014758&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016251&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016519&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21003285&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23015628&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24001202&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010893&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014504&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016761&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016669&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017349&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015405&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015932&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015155&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017468&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24001114&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012788&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014508&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016580&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010392&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016684&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=17000544&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=19018979&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21007488&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21002430&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=22004566&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23007900&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23018107&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24003484&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24007936&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24007925&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010433&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011983&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010595&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013147&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014178&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013716&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012790&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013898&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013423&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013325&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014263&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014629&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012667&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015377&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015975&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016136&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010317&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014999&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015718&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016942&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016098&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017192&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016198&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016487&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015598&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016253&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012979&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016308&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013835&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016379&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017296&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016667&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017096&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017601&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017103&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015804&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015541&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017471&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016486&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=P0004108&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016624&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016845&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016020&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016546&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017234&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017924&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016743&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017330&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016940&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016846&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016965&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016322&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017190&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016841&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017412&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017802&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016499&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017294&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017408&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017428&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015846&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017336&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24008704&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017599&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017312&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017709&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017658&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015544&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015904&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016852&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017387&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24018001&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017834&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017543&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017662&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017390&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017076&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014927&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016076&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010681&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014873&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016916&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017730&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016629&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014818&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014727&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017191&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017537&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014872&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014810&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014805&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24018013&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017984&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017444&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014136&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014817&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014688&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014921&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017803&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017598&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017440&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017505&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017892&

In [66]:
urls_list = ['https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24006928&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017573&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012128&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=L0000104&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014092&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015518&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=22001159&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23005704&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23008491&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015841&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21013249&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=22014277&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015530&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24001916&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24002802&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014788&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016741&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21013096&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017904&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016054&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=22001006&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014333&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24004660&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014157&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012547&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017907&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21002623&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24008626&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017527&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23005252&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24000171&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015331&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011787&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23018094&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016450&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016323&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23003616&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23004562&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23011814&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21007446&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23016780&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016099&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013962&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015317&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=18001569&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013510&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017500&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24007536&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011341&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016640&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24001143&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014861&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014723&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016815&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015988&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=22007314&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24002220&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015580&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015947&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016449&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017888&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017879&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24009362&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013365&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014410&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016592&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011798&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014759&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015587&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=19001540&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24007080&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011257&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011577&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016342&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015496&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017161&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=18013732&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016023&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011113&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014758&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016251&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016519&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21003285&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23015628&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24001202&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010893&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014504&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016761&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016669&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017349&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015405&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015932&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015155&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017468&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24001114&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012788&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014508&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016580&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010392&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016684&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=17000544&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=19018979&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21007488&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=21002430&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=22004566&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23007900&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=23018107&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24003484&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24007936&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24007925&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010433&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24011983&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010595&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013147&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014178&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013716&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012790&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013898&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013423&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013325&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014263&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014629&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012667&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015377&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015975&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016136&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010317&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014999&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015718&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016942&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016098&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017192&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016198&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016487&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015598&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016253&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24012979&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016308&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24013835&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016379&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017296&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016667&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017096&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017601&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017103&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015804&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015541&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017471&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016486&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=P0004108&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016624&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016845&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016020&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016546&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017234&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017924&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016743&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017330&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016940&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016846&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016965&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016322&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017190&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016841&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017412&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017802&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016499&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017294&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017408&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017428&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015846&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017336&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24008704&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017599&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017312&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017709&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017658&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015544&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24015904&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016852&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017387&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24018001&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017834&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017543&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017662&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017390&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017076&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014927&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016076&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24010681&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014873&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016916&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017730&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016629&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014818&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014727&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017191&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017537&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014872&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014810&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014805&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24018013&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017984&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017444&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014136&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014817&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014688&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014921&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017803&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017598&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017440&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017505&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017892&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017896&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24018008&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017736&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017997&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017906&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017741&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017624&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017664&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017304&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017781&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017284&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017519&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017890&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017780&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017961&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017744&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017054&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017742&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016045&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014983&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24017794&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016776&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016780&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24016553&app_tapbar_state=fix', 'https://mticket.interpark.com/Goods/GoodsInfo/info?GoodsCode=24014474&app_tapbar_state=fix']

In [68]:
from bs4 import BeautifulSoup
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import pandas as pd
import GetCategory as cate
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys


### Crawling Setup
# ChromeDriver 경로
chromedriver_path = "C:\\Users\\cokip\\Downloads\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe" # 정확한 파일 경로 입력

# Service 객체 생성
service = Service(chromedriver_path)

# WebDriver 생성
browser = webdriver.Chrome(service=service)

# 암시적 대기
browser.implicitly_wait(3)

# 테스트 URL
# urls = cate.get_urls_list("http://mticket.interpark.com/Genre?Genre=DR")


total = []
for url in urls_list:
    browser = webdriver.Chrome()
    browser.implicitly_wait(3)
    browser.get(url)

    # 팝업 닫기 
    try:
        close_button = WebDriverWait(browser, 10).until(
            EC.presence_of_element_located((By.CLASS_NAME, "popupCloseBtn.is-bottomBtn"))
        )
        browser.execute_script("arguments[0].click();", close_button)
    except Exception as e:
        print(f"Error: {e}")

    while 1:
        try:
            # browser.find_element_by_class_name("moreBtn").send_keys(Keys.ENTER)
            browser.find_element(By.CLASS_NAME, "moreBtn").send_keys(Keys.ENTER)
            time.sleep(2)
        except:
            break



    try:
        browser.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)
    
        playnm = browser.find_element(By.CLASS_NAME, "prdTitle").text
    
        gender_stats = []
        for k in browser.find_elements(By.CLASS_NAME, "statGenderType "):
            gender = k.find_element(By.CLASS_NAME, "statGenderValue").text.rstrip('%')
            gender_stats.append(gender)

        age_stats = []
        for x in browser.find_elements(By.CLASS_NAME, "statAgeType"):
            age = x.find_element(By.CLASS_NAME, "statAgePercent").text.rstrip('%')
            age_stats.append(age)

        row = [playnm] + gender_stats + age_stats
        total.append(row)
        print(f'{playnm}의 예매자 통계를 저장했습니다.')

        browser.close()
    except Exception as e:
                print(f"Error: {e}")
                
    except:
        print("no static")

print(total)

대학로 1위 연극 〈쉬어매드니스〉의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

2025 연극 〈세일즈맨의 죽음〉의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

국립극장 〈마당놀이 모듬전〉의 예매자 통계를 저장했습니다.
연극 ＇타인의 삶＇의 예매자 통계를 저장했습니다.
연극 〈테베랜드〉의 예매자 통계를 저장했습니다.
연극 〈대학살의 신〉의 예매자 통계를 저장했습니다.
연극〈늘근도둑이야기〉의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

행오버의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

16년 블랙코미디 1위 연극 〈죽여주는 이야기〉의 예매자 통계를 저장했습니다.
연극 사랑해 엄마의 예매자 통계를 저장했습니다.
연극 〈2호선세입자〉 : 지하철 생존 코미디의 예매자 통계를 저장했습니다.
연극 한뼘사이의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

국립극단x대전예술의전당 공동제작 연극 ［십이야］- 대전의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

국민 코믹 연극 〈오백에삼십〉 - 대학로 JTN 아트홀 3관의 예매자 통계를 저장했습니다.
뮤직드라마 〈불편한 편의점〉 - 올웨이즈씨어터의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

연극 〈톡톡〉 : 연극열전10_네 번째 작품의 예매자 통계를 저장했습니다.
연극 〈붉은 낙엽〉의 예매자 통계를 저장했습니다.
10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

타오르는 어둠 속에서의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

연극 〈뜨거운 여름〉 : 공연배달서비스 간다 20주년 퍼레이드의 예매자 통계를 저장했습니다.
4D공포연극 〈스위치〉의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

코믹 뮤직 체력극 〈신바람삼대〉 - 대전의 예매자 통계를 저장했습니다.
뮤직드라마 〈불편한 편의점〉 - 부산의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

연극 〈운빨로맨스〉 - 대전의 예매자 통계를 저장했습니다.
연극 〈보이즈 인 더 밴드〉의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

beingbeingbeing의 예매자 통계를 저장했습니다.
연극 〈운빨로맨스〉- 대학로의 예매자 통계를 저장했습니다.
사내연애 보고서의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

국민연극〈라이어1탄〉 - 상명아트홀 1관의 예매자 통계를 저장했습니다.
이머시브씨어터 카지노의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

［서울 대학로］연극 라면의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

영등포아트홀 기획공연 ［호야:好夜］의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

연극 은밀한 연애의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

이홍도 신작 〈꿈의 연극〉의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

이 세상 말고의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

2025 연극 〈친정엄마와 2박 3일〉 - 부천의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

연극 핫식스의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

좀비연극 오마이갓의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]
	(No symbol) [0x00007FF7B8F0A778]
	(No symbol) [0x00007FF7B8F0B8E1]
	GetHandleVerifier [0x00007FF7B93EFCCD+3408029]
	GetHandleVerifier [0x00007FF7B940743F+3504143]
	GetHandleVerifier [0x00007FF7B93FB61D+3455469]
	GetHandleVerifier [0x00007FF7B917BDCB+835995]
	(No symbol) [0x00007FF7B902EB6F]
	(No symbol) [0x00007FF7B902A824]
	(No symbol) [0x00007FF7B902A9BD]
	(No symbol) [0x00007FF7B901A1A9]
	BaseThreadInitThunk [0x00007FFAD0F9259D+29]
	RtlUserThreadStart [0x00007FFAD248AF38+40]

★평점9.5★ 개그콘서트프리뷰/코미디의맛의 예매자 통계를 저장했습니다.
비누향기의 예매자 통계를 저장했습니다.
Error: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF7B90B6CC5+28821]
	(No symbol) [0x00007FF7B9023850]
	(No symbol) [0x00007FF7B8EC578A]
	(No symbol) [0x00007FF7B8F191BE]
	(No symbol) [0x00007FF7B8F194AC]
	(No symbol) [0x00007FF7B8F62647]
	(No symbol) [0x00007FF7B8F3F33F]
	(No symbol) [0x00007FF7B8F5F412]
	(No symbol) [0x00007FF7B8F3F0A3]

In [70]:
df = pd.DataFrame(total, columns=['playnm', 'male', 'female', 'teenage', 'twenty', 'thirty', 'forty', 'fifty'])
df

,playnm,male,female,teenage,twenty,thirty,forty,fifty
0,대학로 1위 연극 〈쉬어매드니스〉,29,71,22.3,46.9,19.7,7.3,3.3
1,2025 연극 〈세일즈맨의 죽음〉,16.8,83.2,4,15.1,30,29.7,17.2
2,국립극장 〈마당놀이 모듬전〉,33.7,66.3,0.8,5,13.1,30.5,26.7
3,연극 ＇타인의 삶＇,15.3,84.7,10.6,26.9,31.8,21.4,7.9
4,연극 〈테베랜드〉,7.8,92.2,9.2,30,34.5,20.7,4.2
...,...,...,...,...,...,...,...,...
233,2025년 경기도극단 〈 창작희곡의 발견 - 부인의 시대 ＆ 우체국에 김영희씨 〉 ...,80,20,0,0,0,40,40
234,국립극단 〈그의 어머니〉,37.9,62.1,10.3,13.8,20.7,20.7,34.5
235,사랑의 죽음. 피비린내가 눈에서 떠나지 않아. 후안 벨몬테,37.5,62.5,9.4,18.8,25,12.5,25
236,국립극장 기획 〈헌치백〉,24.1,75.9,0,6.9,27.6,27.6,37.9
237,당신은 지금 바비레따에 살고 있군요 - 부산,0,100,0,0,0,0,0

In [78]:
df02 = pd.DataFrame(total, columns=['title', 'male', 'female', 'teenage', 'twenty', 'thirty', 'forty', 'fifty'])
df02

,title,male,female,teenage,twenty,thirty,forty,fifty
0,대학로 1위 연극 〈쉬어매드니스〉,29,71,22.3,46.9,19.7,7.3,3.3
1,2025 연극 〈세일즈맨의 죽음〉,16.8,83.2,4,15.1,30,29.7,17.2
2,국립극장 〈마당놀이 모듬전〉,33.7,66.3,0.8,5,13.1,30.5,26.7
3,연극 ＇타인의 삶＇,15.3,84.7,10.6,26.9,31.8,21.4,7.9
4,연극 〈테베랜드〉,7.8,92.2,9.2,30,34.5,20.7,4.2
...,...,...,...,...,...,...,...,...
233,2025년 경기도극단 〈 창작희곡의 발견 - 부인의 시대 ＆ 우체국에 김영희씨 〉 ...,80,20,0,0,0,40,40
234,국립극단 〈그의 어머니〉,37.9,62.1,10.3,13.8,20.7,20.7,34.5
235,사랑의 죽음. 피비린내가 눈에서 떠나지 않아. 후안 벨몬테,37.5,62.5,9.4,18.8,25,12.5,25
236,국립극장 기획 〈헌치백〉,24.1,75.9,0,6.9,27.6,27.6,37.9
237,당신은 지금 바비레따에 살고 있군요 - 부산,0,100,0,0,0,0,0

In [80]:
df02.to_csv("statistics_raw.csv", index=False, encoding="utf-8-sig")

In [76]:
urls01 = pd.DataFrame(urls_list, columns=['url'])
urls01.to_csv("interpark_urls_1211.csv", index=False)